CASE_TYPE = {
    "All": "",
    "Advert Split": "ADS",
    "Advertisement": "ADV",
    "Agricultrual to Residential": "PRIF",
    "Beach Hut": "BEA",
    "Change of Use": "CHA",
    "Circular 7/77": "CI77",
    "Cons Area Consent": "CAC",
    "Crown Dev": "CRO",
    "Deemed Application": "DEAP",
    "Demolish unlisted in cons area": "DEMU",
    "Demolition": "DEM",
    "Dorset CC": "DOR",
    "Enquiry": "ENQ",
    "Established Use": "ESTU",
    "Fell and Prune Trees in a TPO": "TPF/P",
    "Fell Trees in a TPO": "TPF",
    "Full": "FUL",
    "Full Split": "FULS",
    "General Permitted Development": "GPD",
    "Government": "GOV",
    "Hazardous Substances (Hist.)": "HAZH",
    "HazSubstCons": "HAZ",
    "Householder": "HSE",
    "Inspection Address/Copies": "INSP",
    "Lawful Development Cert Existing": "LDCE",
    "Lawful Development Cert Proposed": "LDCP",
    "Listed Building": "LBC",
    "Listed Building - Alter/Extend": "LBCA",
    "Listed Building - Demolition": "LBCD",
    "Mineral (Hist.)": "MINH",
    "Minerals": "MIN",
    "Non Material Changes": "NONMAT",
    "Old Code for Cert of Lawfulness": "CLD",
    "Outline": "OUT",
    "Outline (Historic)": "OUTH",
    "Poole": "POOL",
    "Pre Application - Screening/Scoping": "PRE6",
    "Prior Approval Change of Use Office": "PRIC",
    "Prior Approval for Demolition": "PRIID",
    "Prior Approval Others": "PROTH",
    "Prior Approval Retail to Residential": "PRIR",
    "Prior Approval school/nursery": "PRISN",
    "Prior Approval Storage or Distribution": "SDCRES",
    "Prior Approval Telecoms": "PRIA",
    "Prune Trees in a TPO": "TPP",
    "Regulation 3": "REG3",
    "Regulation 4/5": "REG",
    "Reserved Matters": "RES",
    "Reserved Matters (Historic)": "RESH",
    "S53 Determination": "S53D",
    "Statutory Undertakers": "STAT",
    "Telecommunications": "TEL",
    "Temporary": "TEMP",
    "Time Limit Extension": "TIME",
    "Tree Historic": "TPTRE",
    "Trees (TPO)": "TPO",
    "Treeworks": "TPTW",
    "Unknown (Historic)": "UNK",
    "WASTE": "WAST",
    "Work on a Hedgerow": "TPH",
    "Work on Trees in a Conservation Area": "TPCA"
}

WARD = {
    "All": "",
    "Alderney & Bourne Valley": "ABVY",
    "Bearwood & Merley": "BWMY",
    "Broadstone": "BSTN",
    "Canford Cliffs": "CFCF",
    "Canford Heath": "CFHH",
    "Creekmoor": "CRKM",
    "Hamworthy": "HMWY",
    "Kinson": "KNSN",
    "Newtown & Heatherlands": "NEWH",
    "Oakdale": "OAKD",
    "Parkstone": "PARK",
    "Penn Hill": "PENH",
    "Poole Town": "PLET",
    "Talbot & Branksome Woods": "TBWD",
    "Ward1": "WRD1"
}

CONSERVATION_AREA = {
    "All": "",
    "Ashington": "CA14",
    "Ashley Cross": "CA02",
    "Beach Road": "CA03",
    "Branksome Park": "CA04",
    "Branksome Park and Chine Gardens": "CA26",
    "Brunstead Road": "CA05",
    "Canford Cliffs": "CA06",
    "Canford Cliffs Village": "CA25",
    "Canford Magna": "CA07",
    "Chester Road": "CA23",
    "Compton Acres": "CA17",
    "Evening Hill": "CA08",
    "Harbour Heights Estate": "CA19",
    "Haven Road": "CA16",
    "Heckford Park": "CA22",
    "High Street": "CA09",
    "North Canford Cliffs": "CA15",
    "Oakley Lane": "CA10",
    "Old Town": "CA11",
    "Poole Park": "CA12",
    "Ridgeway and Broadstone Park": "CA21",
    "Sandbanks": "CA18",
    "The Avenue": "CA01",
    "The Quay": "CA13",
    "Town Centre Heritage": "CA24",
    "Tudor and Golf Links Road": "CA20"
}

STATUS = {
    "All": "",
    "Appeal decided": "Appeal decided",
    "Appeal lodged": "Appeal lodged",
    "Decided": "Decided",
    "Registered": "Registered",
    "Unknown": "Unknown"
}

DECISION = {
    "All": "",
    "Approval CLEUD or CLOPUD": "APCL",
    "Called in by ODPM": "CALL",
    "Conditional Approval": "COAP",
    "Consultations by Government Departments": "GOVC",
    "Council Deemed Consent": "DEEC",
    "De-minimus": "DEMI",
    "Decision Deferred": "DECD",
    "Deemed Consent": "DECO",
    "Deemed Consent Prior Approval": "DEPA",
    "Deemed Refusal": "DERE",
    "Disposed Application": "DISP",
    "General Permitted Develop PA Granted": "GPDC",
    "General Permitted Development PA Refused": "GPDR",
    "General Permitted Devlopment PA Not Reqd": "GPDD",
    "Government Office of South West": "GOSW",
    "Grant": "GR",
    "Grant of Deemed Consent": "GRDE",
    "Grant of Prior Approval": "PA G",
    "Grant Section 106": "G106",
    "Grant Subject TO CIL Contribution": "GCIL",
    "Grant Subject to Unilateral Undertaking": "GRUN",
    "Grant Upfront Payment": "GRUP",
    "Grant with Conditions": "GRCO",
    "Migrated Code": "S",
    "Miscellaneous": "MISC",
    "No objection": "NOOB",
    "No objection with conditions": "NOBC",
    "Non-Determination": "NOND",
    "PA Not required": "PANO",
    "Permitted Development (DC)": "PDV",
    "Permitted Development Enquiries (No)": "PDNO",
    "Permitted Development Enquiries (Yes)": "PD",
    "Pre-App Response Provided": "PREA",
    "Prior approval required": "PARE",
    "Raised No Objection": "RNO",
    "Raised No Objection with conditions (CA)": "NCON",
    "Refer to ODPM": "DETR",
    "Refusal of CLEUD or CLOPUD": "RECL",
    "Refuse": "REF",
    "Revoked": "REVO",
    "Split Decision": "SPL",
    "Withdrawn": "WDN"
}

APPEAL_STATUS = {
    "All": "",
    "Appeal decided": "Appeal decided",
    "Appeal lodged": "Appeal lodged",
    "Awaiting decision": "Awaiting decision",
    "Decided": "Decided",
    "Registered": "Registered",
    "Unknown": "Unknown"
}

APPEAL_DECISION = {
    "All": "",
    "Allowed": "A",
    "Dismissed": "D",
    "Mixed": "M",
    "Non Determination": "N",
    "Other": "O",
    "Split Decision": "S",
    "Withdrawn": "W"
}

DEVELOPMENT_TYPE = {
    "All": "",
    "Advertisements": "Q22",
    "Certificates of lawful development": "Q26",
    "Change of Use": "Q20",
    "Conservation area consents": "Q25",
    "General Permitted Development Type Apps": "Q29",
    "Householder developments": "Q21",
    "Large Scale Dwelling": "Q01",
    "Large Scale Gen.Indus/storage/warehouse": "Q03",
    "Large Scale Gypsy & Traveller sites": "Q05",
    "Large Scale Offices/R&D/light industry": "Q02",
    "Large Scale Retail distrib. &servicing": "Q04",
    "Listed Building consents (alter/extend)": "Q23",
    "Listed Building consents (demolish)": "Q24",
    "Minerals Processing": "Q19",
    "Minor Dwellings": "Q13",
    "Minor General industry/storage/warehouse": "Q15",
    "Minor Gypsy & Traveller site": "Q17",
    "Minor Offices/R&D/light industry": "Q14",
    "Minor Retail distribution & servicing": "Q16",
    "Non Material Change Applications": "Q28",
    "Notifications": "Q27",
    "Other Large Scale developments": "Q06",
    "Other minor development": "Q18"
}

EDDC_PARISH = {"": "",
               'Alderholt': 'E04003362',
               'Burton': 'E04003360',
               'Chalbury': 'E04003363',
               'Colehill': 'E04012462',
               'Colehill (OLD BOUNDARY)': 'E04003364',
               'Corfe Mullen': 'E04003365',
               'Cranborne': 'E04003366',
               'Crichel': 'E04012453',
               'Edmondsham': 'E04003367',
               'Ferndown Town': 'E04012463',
               'Ferndown Town (OLD BOUNDARY)': 'E04003368',
               'Gussage All Saints': 'E04003369',
               'Gussage St. Michael': 'E04003370',
               'Gussage St. Michael (OLD CODE)': 'GUSSGE',
               'Hinton': 'E04012454',
               'Hinton Martell (OLD BOUNDARY)': 'E04003371',
               'Hinton Parva (OLD BOUNDARY)': 'E04003372',
               'Holt': 'E04003373',
               'Horton': 'E04012456',
               'Horton (OLD BOUNDARY)': 'E04003374',
               'Hurn': 'E04003361',
               'Long Crichel (OLD BOUNDARY)': 'E04003375',
               'Moor Crichel (OLD BOUNDARY)': 'E04003376',
               'Pamphill': 'E04003377',
               'Pentridge (OLD BOUNDARY)': 'E04003378',
               'Shapwick': 'E04003380',
               'Sixpenny Handley (OLD BOUNDARY)': 'E04003381',
               'Sixpenny Handley and Pentridge': 'E04012455',
               'St. Leonards and St. Ives': 'E04003379',
               'Sturminster Marshall': 'E04003382',
               'Verwood': 'E04012457',
               'Verwood (OLD BOUNDARY)': 'E04003383',
               'West Moors': 'E04012459',
               'West Moors (OLD BOUNDARY)': 'E04003384',
               'West Parley': 'E04012461',
               'West Parley (OLD BOUNDARY)': 'E04003385',
               'Wimborne Minster': 'E04012464',
               'Wimborne Minster (OLD BOUNDARY)': 'E04003386',
               'Wimborne St. Giles': 'E04003387',
               'Witchampton': 'E04003388',
               'Woodlands': 'E04003389'}

EDDC_WARD = {'': '',
             'Alderholt': 'E05009515',
             'Ameysford': 'E05009516',
             'Burton & Winkton': 'E05003660',
             'Colehill East': 'E05009517',
             'Colehill West': 'E05009518',
             'Colehill and Wimborne Minster East': '9',
             'Corfe Mullen': 'E05009519',
             'Cranborne Chase': '3',
             'Cranborne and Alderholt': '4',
             'Crane': 'E05009520',
             'Ferndown Central': 'E05009521',
             'Ferndown North': '10',
             'Ferndown South': '11',
             'Grange': 'E05003661',
             'Hampreston and Longham': 'E05009522',
             'Handley Vale': 'E05009523',
             'Highcliffe': 'E05003662',
             'Jumpers': 'E05003663',
             'Mudeford & Friars Cliff': 'E05003664',
             'North Highcliffe & Walkford': 'E05003665',
             'Parley': 'E05009524',
             'Portfield': 'E05003666',
             'Purewell & Stanpit': 'E05003667',
             "St Catherine's and Hurn": 'E05003668',
             'St Leonards': 'E05009525',
             'St Leonards and St Ives': '7',
             'Stour': 'E05009526',
             'Stour and Allen Vale': '2',
             'Town Centre': 'E05003669',
             'Verwood': '5',
             'Verwood East': 'E05009527',
             'Verwood West': 'E05009528',
             'West Highcliffe': 'E05003670',
             'West Moors and Holt': 'E05009529',
             'West Moors and Three Legged Cross': '6',
             'West Parley': '12',
             'Wimborne Minster': 'E05009530'}

EDDC_DECISION_TYPE = {'': '',
                      'Accept': 'ACC',
                      'Approval': 'APP',
                      'Building Control': '$$OPTGROUP$$OPTGROUP$$',
                      'Check Decision Notice': 'CHK',
                      'Conditional Approval': 'CAP',
                      'Does not require consent': 'NRC',
                      'Does require consent': 'DRC',
                      'Granted': 'GRA',
                      'Initial Notice Accept': 'INA',
                      'Initial Notice Invalid': 'INI',
                      'Invalid': 'INV',
                      'Lawful': 'LAW',
                      'No objections raised': 'NOB',
                      'Non-determination': 'NON',
                      'Not Lawful': 'NLA',
                      'Objection Raised': 'OBJ',
                      'PD - Application Required': 'PDA',
                      'PD - Within PD': 'PDR',
                      'Planning': '$$OPTGROUP$$OPTGROUP$$',
                      'Prior approval not required': 'PAN',
                      'Prior approval required': 'PAR',
                      'Quashed': 'QUA',
                      'Refused': 'REF',
                      'Reject': 'REJ',
                      'Split decision': 'SPL',
                      'Withdraw/re-deposit': 'WRD',
                      'Withdrawn': 'W',
                      'Written response given': 'WRG'}

EDDC_APPLICATION_TYPE = {'': '',
                         'Certificate of Appropriate Alternative Development': 'CAAD',
                         'Certificate of Lawfulness for existing use or development': 'CLE',
                         'Certificate of Lawfulness for proposed use or development': 'CLP',
                         'Certificate of Lawfulness for proposed works to a Listed Building': 'CLPLB',
                         'Change Of Use': 'COU',
                         'Consent to display an Advertisement': 'ADV',
                         'Crown Development (Circular 18/84)': 'CRN',
                         'Demolition of Unlisted Building in a Conservation Area': 'DCONS',
                         'Discharge Condition': 'DIS',
                         'Felling Licence': 'FLC',
                         'Full Planning Permission': 'FUL',
                         'Hazardous Substances Consent': 'HAZ',
                         'Historic EDDC applications': 'HST',
                         'Householder Application': 'HOU',
                         'Important Hedgerows': 'HREG',
                         'Listed Building Consent': 'LB',
                         'Local Authority': 'DCC',
                         'Modify Or Discharge A Planning Obligation': 'SEC',
                         'Non-Material Amendment': 'NMA',
                         'Outline Planning Permission': 'OUT',
                         'Permission In Principle - Stage 1': 'PIP',
                         'Permission In Principle - Stage 2': 'PIT',
                         'Permitted Development Notification': 'PDNOT',
                         'Pre-application (letter)': 'PAL',
                         'Pre-application (meeting)': 'PAM',
                         'Prior Notification (Demolition)': 'PNDEM',
                         'Prior Notification (Electricity Stations and Overhead Lines)': 'PNE',
                         'Prior Notification (Forestry or Agricultural)': 'PNFAG',
                         'Prior Notification (Part 1.A: Householder)': 'PNHH',
                         'Prior Notification (Part 14.J:Photo-voltaics on Non-Domestic Buildings)': 'PNPHV',
                         'Prior Notification (Part 3. P: Storage/Distribution Centre to Dwellinghouse': 'PNSDD',
                         'Prior Notification (Part 3.C: Various to Restaurant or cafe)': 'PNVRC',
                         'Prior Notification (Part 3.J: Various to assembly & leisure)': 'PNVAL',
                         'Prior Notification (Part 3.M: Retail to Dwellinghouse)': 'PNRD',
                         'Prior Notification (Part 3.N: Specified  suis generis uses to Dwellinghouse)': 'PNSGD',
                         'Prior Notification (Part 3.O: Office to Dwellinghouse)': 'PNOD',
                         'Prior Notification (Part 3.PA: Light Industrial to Dwellinghouse)': 'PNLID',
                         'Prior Notification (Part 3.Q: from Agricultural to Dwellinghouse)': 'PNAGD',
                         'Prior Notification (Part 3.R: from Agricultural to Flexible Commercial Use)': 'PNAGF',
                         'Prior Notification (Part 3.S: from Agricultural to State Funded School/Registered': 'PNAGS',
                         'Prior Notification (Part 3.T: Various to State Funded School)': 'PNVS',
                         'Prior Notification (Part 4.D: Shops, financial etc to temporary flexible use)': 'PNSFX',
                         'Prior Notification (Part 4.E: Temporary use for film making)': 'PNTF',
                         'Prior Notification (Part 7.C: Collection Facility within Shop Curtilage)': 'PNCSC',
                         'Prior Notification (Telecoms)': 'PNTEL',
                         'Regulation 14 - Dead and Dangerous': 'REG14',
                         'Removal or Variation of Condition': 'CONDR',
                         'Reserved Matters': 'RM',
                         'Scoping Request - EIA': 'SCOPE',
                         'Screening Request - EIA': 'SCRN',
                         'Stopping up or Diversion of a Footpath or Bridleway': 'FTP',
                         'Tree work in a Conservation Area': 'TCA',
                         'Tree work to tree/s subject to a TPO': 'TTPO'}

EDDC_METHOD = {'': '',
               'Hearing': 'HR',
               'Householder ': 'HH',
               'Inquiry': 'IN',
               'Shop Front Fast Track': 'SF',
               'Tree Fast Track': 'TRF',
               'Written Representations': 'WR'}

EDDC_DECISION = {'': '',
                 'Allowed': 'ALL',
                 'Check': 'CHK',
                 'Dismissed': 'DIS',
                 'Invalid': 'INV',
                 'No Further Action': 'NFA',
                 'Quashed': 'QUA',
                 'Split Decision': 'SPL',
                 'Withdrawn': 'WD'}
