CASE_TYPE = {
  "All": "",
  "Advert Split": "ADS",
  "Advertisement": "ADV",
  "Agricultrual to Residential": "PRIF",
  "Beach Hut": "BEA",
  "Change of Use": "CHA",
  "Circular 7/77": "CI77",
  "Cons Area Consent": "CAC",
  "Crown Dev": "CRO",
  "Deemed Application": "DEAP",
  "Demolish unlisted in cons area": "DEMU",
  "Demolition": "DEM",
  "Dorset CC": "DOR",
  "Enquiry": "ENQ",
  "Established Use": "ESTU",
  "Fell and Prune Trees in a TPO": "TPF/P",
  "Fell Trees in a TPO": "TPF",
  "Full": "FUL",
  "Full Split": "FULS",
  "General Permitted Development": "GPD",
  "Government": "GOV",
  "Hazardous Substances (Hist.)": "HAZH",
  "HazSubstCons": "HAZ",
  "Householder": "HSE",
  "Inspection Address/Copies": "INSP",
  "Lawful Development Cert Existing": "LDCE",
  "Lawful Development Cert Proposed": "LDCP",
  "Listed Building": "LBC",
  "Listed Building - Alter/Extend": "LBCA",
  "Listed Building - Demolition": "LBCD",
  "Mineral (Hist.)": "MINH",
  "Minerals": "MIN",
  "Non Material Changes": "NONMAT",
  "Old Code for Cert of Lawfulness": "CLD",
  "Outline": "OUT",
  "Outline (Historic)": "OUTH",
  "Poole": "POOL",
  "Pre Application - Screening/Scoping": "PRE6",
  "Prior Approval Change of Use Office": "PRIC",
  "Prior Approval for Demolition": "PRIID",
  "Prior Approval Others": "PROTH",
  "Prior Approval Retail to Residential": "PRIR",
  "Prior Approval school/nursery": "PRISN",
  "Prior Approval Storage or Distribution": "SDCRES",
  "Prior Approval Telecoms": "PRIA",
  "Prune Trees in a TPO": "TPP",
  "Regulation 3": "REG3",
  "Regulation 4/5": "REG",
  "Reserved Matters": "RES",
  "Reserved Matters (Historic)": "RESH",
  "S53 Determination": "S53D",
  "Statutory Undertakers": "STAT",
  "Telecommunications": "TEL",
  "Temporary": "TEMP",
  "Time Limit Extension": "TIME",
  "Tree Historic": "TPTRE",
  "Trees (TPO)": "TPO",
  "Treeworks": "TPTW",
  "Unknown (Historic)": "UNK",
  "WASTE": "WAST",
  "Work on a Hedgerow": "TPH",
  "Work on Trees in a Conservation Area": "TPCA"
}

WARD = {
  "All": "",
  "Alderney & Bourne Valley": "ABVY",
  "Bearwood & Merley": "BWMY",
  "Broadstone": "BSTN",
  "Canford Cliffs": "CFCF",
  "Canford Heath": "CFHH",
  "Creekmoor": "CRKM",
  "Hamworthy": "HMWY",
  "Kinson": "KNSN",
  "Newtown & Heatherlands": "NEWH",
  "Oakdale": "OAKD",
  "Parkstone": "PARK",
  "Penn Hill": "PENH",
  "Poole Town": "PLET",
  "Talbot & Branksome Woods": "TBWD",
  "Ward1": "WRD1"
}

CONSERVATION_AREA = {
  "All": "",
  "Ashington": "CA14",
  "Ashley Cross": "CA02",
  "Beach Road": "CA03",
  "Branksome Park": "CA04",
  "Branksome Park and Chine Gardens": "CA26",
  "Brunstead Road": "CA05",
  "Canford Cliffs": "CA06",
  "Canford Cliffs Village": "CA25",
  "Canford Magna": "CA07",
  "Chester Road": "CA23",
  "Compton Acres": "CA17",
  "Evening Hill": "CA08",
  "Harbour Heights Estate": "CA19",
  "Haven Road": "CA16",
  "Heckford Park": "CA22",
  "High Street": "CA09",
  "North Canford Cliffs": "CA15",
  "Oakley Lane": "CA10",
  "Old Town": "CA11",
  "Poole Park": "CA12",
  "Ridgeway and Broadstone Park": "CA21",
  "Sandbanks": "CA18",
  "The Avenue": "CA01",
  "The Quay": "CA13",
  "Town Centre Heritage": "CA24",
  "Tudor and Golf Links Road": "CA20"
}

STATUS = {
  "All": "",
  "Appeal decided": "Appeal decided",
  "Appeal lodged": "Appeal lodged",
  "Decided": "Decided",
  "Registered": "Registered",
  "Unknown": "Unknown"
}

DECISION = {
  "All": "",
  "Approval CLEUD or CLOPUD": "APCL",
  "Called in by ODPM": "CALL",
  "Conditional Approval": "COAP",
  "Consultations by Government Departments": "GOVC",
  "Council Deemed Consent": "DEEC",
  "De-minimus": "DEMI",
  "Decision Deferred": "DECD",
  "Deemed Consent": "DECO",
  "Deemed Consent Prior Approval": "DEPA",
  "Deemed Refusal": "DERE",
  "Disposed Application": "DISP",
  "General Permitted Develop PA Granted": "GPDC",
  "General Permitted Development PA Refused": "GPDR",
  "General Permitted Devlopment PA Not Reqd": "GPDD",
  "Government Office of South West": "GOSW",
  "Grant": "GR",
  "Grant of Deemed Consent": "GRDE",
  "Grant of Prior Approval": "PA G",
  "Grant Section 106": "G106",
  "Grant Subject TO CIL Contribution": "GCIL",
  "Grant Subject to Unilateral Undertaking": "GRUN",
  "Grant Upfront Payment": "GRUP",
  "Grant with Conditions": "GRCO",
  "Migrated Code": "S",
  "Miscellaneous": "MISC",
  "No objection": "NOOB",
  "No objection with conditions": "NOBC",
  "Non-Determination": "NOND",
  "PA Not required": "PANO",
  "Permitted Development (DC)": "PDV",
  "Permitted Development Enquiries (No)": "PDNO",
  "Permitted Development Enquiries (Yes)": "PD",
  "Pre-App Response Provided": "PREA",
  "Prior approval required": "PARE",
  "Raised No Objection": "RNO",
  "Raised No Objection with conditions (CA)": "NCON",
  "Refer to ODPM": "DETR",
  "Refusal of CLEUD or CLOPUD": "RECL",
  "Refuse": "REF",
  "Revoked": "REVO",
  "Split Decision": "SPL",
  "Withdrawn": "WDN"
}

APPEAL_STATUS = {
  "All": "",
  "Appeal decided": "Appeal decided",
  "Appeal lodged": "Appeal lodged",
  "Awaiting decision": "Awaiting decision",
  "Decided": "Decided",
  "Registered": "Registered",
  "Unknown": "Unknown"
}

APPEAL_DECISION = {
  "All": "",
  "Allowed": "A",
  "Dismissed": "D",
  "Mixed": "M",
  "Non Determination": "N",
  "Other": "O",
  "Split Decision": "S",
  "Withdrawn": "W"
}

DEVELOPMENT_TYPE = {
  "All": "",
  "Advertisements": "Q22",
  "Certificates of lawful development": "Q26",
  "Change of Use": "Q20",
  "Conservation area consents": "Q25",
  "General Permitted Development Type Apps": "Q29",
  "Householder developments": "Q21",
  "Large Scale Dwelling": "Q01",
  "Large Scale Gen.Indus/storage/warehouse": "Q03",
  "Large Scale Gypsy & Traveller sites": "Q05",
  "Large Scale Offices/R&D/light industry": "Q02",
  "Large Scale Retail distrib. &servicing": "Q04",
  "Listed Building consents (alter/extend)": "Q23",
  "Listed Building consents (demolish)": "Q24",
  "Minerals Processing": "Q19",
  "Minor Dwellings": "Q13",
  "Minor General industry/storage/warehouse": "Q15",
  "Minor Gypsy & Traveller site": "Q17",
  "Minor Offices/R&D/light industry": "Q14",
  "Minor Retail distribution & servicing": "Q16",
  "Non Material Change Applications": "Q28",
  "Notifications": "Q27",
  "Other Large Scale developments": "Q06",
  "Other minor development": "Q18"
}

